
services:
  mlflow:
    image: python:3.11-slim
    container_name: mlflow
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      sh -c "pip install --no-cache-dir mlflow &&
             mlflow server --host 0.0.0.0 --port 5000
             --backend-store-uri sqlite:///mlflow.db
             --default-artifact-root /app/mlruns"
    ports:
      - "5000:5000"

  api:
    build: .
    container_name: risk-demand-api
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000 --reload
